// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StyleInTreeView;

internal sealed partial class Vsix
{
    public const string Id = "StyleInTreeView.f6989371-a316-4559-baba-396fe6d787c9";
    public const string Name = "StyleInTreeView";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Tim Heuer";
    public const string Tags = "";
}
